### ISSUE TITLE
Support federation protocol

### ISSUE THREAD

**Issue by mcollina** [mcollina/fastify-gql#97]
In https://www.apollographql.com/docs/apollo-server/federation/federation-spec/, the Apollo fedaration protocol is defined. We should support the federation protocol so that fastify-gql services can be exposed by the federation server.

**Comment by PacoDu** [comment]
Do you intent to implement the gateway server or only to make fastify-gql compatible with the federation protocol ?

Note that, for now, federation is incompatible with subscriptions (Probably due to apollo gateway implementation). Because of this limitation I've not personally tested the federation yet.

I don't know why exactly, nor if we have a way to make it work but it would definitively be a great feature. (But this would probably require a custom implementation of a fastify-gql-gateway)

**Comment by mcollina** [comment]
Step 1 is to be able to deploy fastify-gql behind the apollo gateway.
Step 2 is to build a `fastify-gql-gateway`.

**Comment by ericlewis** [comment]
I am highly interested in step 2! The work required for it could be greatly improved upon from how Apollo-server currently works.

**Comment by mcollina** [comment]
Step 1 has shipped in v3.1.0

**Comment by mcollina** [comment]
Step 2 has shipped in v3.2.0
